### ISSUE TITLE
New Content Format

### ISSUE THREAD

**Issue by gmcerveny** [ArtfulMediumLabs/youthbeat-lessons#2]
1. Title only on top
2. Increase font below
3. Use font, emphasis, symbol, numbered list, div border/background, or “Action Steps” subtitle to differentiate activities

![TitleOnly](https://user-images.githubusercontent.com/45122/151220396-cad27c0e-a84c-4fbd-b204-553db3956d3f.png)

**Comment by ghost** [comment]
Content layout and styling has been updated in #5.
